server:
  port: 8080

spring:
  datasource:
    url:  jdbc:mysql://${MYSQL_HOST:localhost}:3306/consume?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USERNAME:your-username}
    password: ${MYSQL_PASSWORD:your-password}
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: 6379
      password: ${REDIS_PASSWORD:}
      database: 0
      lettuce:
        pool:
          max-active: 10
          max-idle: 8
          min-idle: 0
          max-wait: -1ms
      timeout: 3000ms

jwt:
  secret: "siersi"
  access-token-expiration: 30
  refresh-token-expiration: 7
  salt: "siersi"

aliyun:
  oss:
    endpoint: your-endpoint
    access-key-id: your-key-id
    access-key-secret: your-key-secret
    bucket-name: your-bucket-name
    url-prefix: your-url-prefix

Siliconflow:
  api:
    qwen:
      model: Qwen/Qwen3-Next-80B-A3B-Instruct
      url: https://api.siliconflow.cn/v1/chat/completions
      key: your-key